exports.authors = [
  ['Jane Austen', 'An English novelist known for her sharp wit and observations of society.'],
  ['George Orwell', 'An English novelist and essayist exploring power, truth, and social justice.'],
  [
    'Virginia Woolf',
    'A pioneering modernist writer with a distinctive stream of consciousness style.',
  ],
  ['Mary Shelley', 'An English author whose work helped shape modern science fiction.'],
  [
    'F. Scott Fitzgerald',
    'An American novelist who chronicled the hopes and contradictions of the Jazz Age.',
  ],
  ['Charlotte Brontë', 'An English novelist known for fiercely independent protagonists.'],
  ['Herman Melville', 'An American writer exploring adventure, obsession, and the sea.'],
  ['Louisa May Alcott', 'An American novelist whose stories celebrate family and self discovery.'],
  ['Oscar Wilde', 'An Irish playwright and novelist celebrated for his wit.'],
  ['Arthur Conan Doyle', 'A Scottish writer who created the detective Sherlock Holmes.'],
  ['Lewis Carroll', 'An English author known for imaginative fiction and playful logic.'],
  [
    'Frances Hodgson Burnett',
    'A British American novelist whose stories explore hope and belonging.',
  ],
];
exports.categories = [
  ['Classics', 'Enduring stories for every generation.'],
  ['Fiction', 'Imagined worlds and unforgettable people.'],
  ['Mystery', 'Puzzles, detectives, and discoveries.'],
  ['Science Fiction', 'New possibilities beyond the everyday.'],
  ['Romance', 'Stories of connection and the human heart.'],
  ['Adventure', 'Journeys into the unknown.'],
  ['Children’s Literature', 'Big stories for young readers.'],
  ['Gothic', 'Atmosphere, secrets, and the uncanny.'],
  ['Modernism', 'New ways of seeing and telling.'],
  ['Social Commentary', 'Stories that examine the world we share.'],
];
// Indexes below are references into the author and category arrays above.
exports.books = [
  [
    'Pride and Prejudice',
    '9780141439518',
    1813,
    [0],
    [0, 1, 4],
    'Elizabeth Bennet navigates family, first impressions, and the unexpected possibilities of love.',
  ],
  [
    'Nineteen Eighty-Four',
    '9780451524935',
    1949,
    [1],
    [0, 1, 3, 9],
    'A searching exploration of surveillance, language, and the struggle to hold on to truth.',
  ],
  [
    'A Room of One’s Own',
    '9780156787338',
    1929,
    [2],
    [8, 9],
    'A landmark essay on creativity, independence, and the conditions that allow a writer to flourish.',
  ],
  [
    'Frankenstein',
    '9780141439471',
    1818,
    [3],
    [0, 3, 7],
    'A scientist brings life into the world and confronts the responsibilities of his creation.',
  ],
  [
    'The Great Gatsby',
    '9780743273565',
    1925,
    [4],
    [0, 1, 9],
    'On Long Island, lavish parties conceal a longing for an elusive past.',
  ],
  [
    'Jane Eyre',
    '9780141441146',
    1847,
    [5],
    [0, 4, 7],
    'A young governess seeks belonging while remaining true to her own convictions.',
  ],
  [
    'Moby-Dick',
    '9780142437247',
    1851,
    [6],
    [0, 5],
    'An ocean voyage becomes an unforgettable meditation on obsession and the natural world.',
  ],
  [
    'Little Women',
    '9780147514011',
    1868,
    [7],
    [0, 1],
    'Four sisters grow, dream, and find their own paths through a changing world.',
  ],
  [
    'The Picture of Dorian Gray',
    '9780141439570',
    1890,
    [8],
    [0, 7],
    'A beautiful portrait reveals the hidden cost of a life without consequences.',
  ],
  [
    'The Adventures of Sherlock Holmes',
    '9780140439076',
    1892,
    [9],
    [0, 2],
    'A collection of ingenious cases solved by the famous Baker Street detective.',
  ],
  [
    'Alice’s Adventures in Wonderland',
    '9780141439761',
    1865,
    [10],
    [5, 6],
    'A curious young reader tumbles into a world where the ordinary rules no longer apply.',
  ],
  [
    'The Secret Garden',
    '9780141321066',
    1911,
    [11],
    [0, 6],
    'An overlooked garden becomes a place of renewal, friendship, and discovery.',
  ],
  [
    'Voices of the English Novel',
    '9780000000001',
    2020,
    [0, 2, 5],
    [0, 8, 9],
    'A sample library anthology bringing three influential literary voices together.',
  ],
];
